fix sysusers in noninteractive case
nix-community/nixos-images pull request #261
Opened 2024-08-02 06:22 UTC by Mic92

2024-08-02 06:43 UTC, flokli requested changes

2024-08-02 06:43 UTC, flokli commented on nix/noninteractive.nix
> +  # normal users are not allowd with sys-users https://github.com/NixOS/nixpkgs/pull
```suggestion
  # normal users are not allowed with sys-users .
  # see https://github.com/NixOS/nixpkgs/pull/328926
```

2024-08-02 07:09 UTC, Mic92 commented on nix/noninteractive.nix
> +  # normal users are not allowd with sys-users https://github.com/NixOS/nixpkgs/pull
Applied.

2024-08-02 07:17 UTC, Mic92 commented on nix/noninteractive.nix
> +  # normal users are not allowd with sys-users https://github.com/NixOS/nixpkgs/pull
Done.

2024-08-02 08:13 UTC, nikstur approved these changes

2024-08-02 08:13 UTC, nikstur commented on nix/noninteractive.nix
> +  users.users.nixos.group = "nixos";
nit: 

```suggestion
  users.users.nixos = {
    isSystemUser = true;
    isNormalUser = lib.mkForce false;
    group = "nixos";
  };
```

2024-08-02 08:31 UTC, merged

2024-08-05 11:42 UTC, evrim commented
Rationale: see https://github.com/NixOS/nixpkgs/pull/328926